service: playads-batch

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  cron:
    handler: app.main
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  secondCron:
    handler: app.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
